# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Ivaylo Sakelariev
email: ivaylo.sakelariev@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Marketer turned Data Scientist
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ivaylo.xyz" # the base hostname & protocol for your site

# Social media profiles - feel free to add more here
twitter_username: sakelariev
github_username:  Sakelariev
facebook_username: ivaylo.sakelariev
#instagram_username: beyonce
#stackoverflow_url: https://
# googleplus_username: BobMarley
#skype_username: echo123
#linkedin_url: https://

# Address information
# address_street: 3034 Melrose Place
address_city: Sofia
address_state: Bulgaria
# address_zip: 90201

# Build settings
markdown: kramdown
plugins:
  - jekyll-sitemap
